### ISSUE TITLE
Less spammy error reporting

### ISSUE THREAD

**Issue by ggreer** [Floobits/floobits-intellij#176]
I'm not sure how it's failing, but one guy is sending us hundreds of error reports:

    IntelliJ IDEA-13-1.3 1.3.3 (Windows 8-6.2)

    Direct buffer memory
    java.lang.OutOfMemoryError: Direct buffer memory
      at java.nio.Bits.reserveMemory(Bits.java:658)
      at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
      at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306)
      at io.fletty.buffer.UnpooledUnsafeDirectByteBuf.allocateDirect(UnpooledUnsafeDirectByteBuf.java:108)
      at io.fletty.buffer.UnpooledUnsafeDirectByteBuf.<init>(UnpooledUnsafeDirectByteBuf.java:69)
      at io.fletty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:50)
      at io.fletty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
      at io.fletty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146)
      at io.fletty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:83)
      at io.fletty.handler.ssl.SslHandler.wrap(SslHandler.java:435)
      at io.fletty.handler.ssl.SslHandler.flush(SslHandler.java:421)
      at io.fletty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:696)
      at io.fletty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:677)
      at io.fletty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
      at io.fletty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:696)
      at io.fletty.channel.DefaultChannelHandlerContext.access$1600(DefaultChannelHandlerContext.java:30)
      at io.fletty.channel.DefaultChannelHandlerContext$WriteAndFlushTask.write(DefaultChannelHandlerContext.java:1000)
      at io.fletty.channel.DefaultChannelHandlerContext$AbstractWriteTask.run(DefaultChannelHandlerContext.java:934)
      at io.fletty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
      at io.fletty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
      at io.fletty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
      at java.lang.Thread.run(Thread.java:724)

**Comment by btipling** [comment]
We don't send out of memory errors anymore.
